routes/web.php
<?php

use App\Events\SendMessage;
use App\Events\GraficoEvent;
use App\Events\PublicMessage;
use App\Events\PrivateMessage;
use App\Events\CasillacheckEvent;
use App\Http\Controllers\ActivityLogController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\KpisController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\DeudaController;
use App\Http\Controllers\EventController;
use App\Http\Controllers\CuentaController;
use App\Http\Controllers\NominaController;
use App\Http\Controllers\ReciboController;
use App\Http\Controllers\EmpresaController;
use App\Http\Controllers\PermisoController;
use App\Http\Controllers\SeguimientoController;
use App\Http\Controllers\TimeUserSessionController;



Route::middleware('RegisterLog')->group(function () { //Registro de actividad Logs
    Route::resource('log', ActivityLogController::class);

    Route::get('/', function () {
        return view('auth.login');
        //return view('welcome');
    });

    Route::get('/chat', function () {
        event(new PublicMessage());
        return view('socket');
    });

    Route::get('/disparo', function () {
        return view('webSocket.socket');
        //return view('welcome');
    });

    Route::get('/socket', function () {
        $event = event(new SendMessage("hola"));
        $event = event(new PublicMessage("publico"));
        //$user = auth()->user();
        //$event = event(new PrivateMessage($user));
        return ('Event Run Successfully.');
    });

    //se debe pasar los datos al websocket por esta ruta
    Route::get('/grafico', function () {
        $event = event(new GraficoEvent("hhhh", null, null));
        return ('Event Run Successfully.');
    });


    Route::group(['middleware' => ['auth']], function () {
        //reidrect user segun rol
        Route::get('/', [HomeController::class, 'index'])->name('home');
        Route::resource('nomina', NominaController::class);
        
        Route::resource('deuda', DeudaController::class);
        Route::resource('pago', CuentaController::class);
        Route::resource('cuenta', CuentaController::class);
        Route::put('cuenta/change/{id}', [CuentaController::class, 'changeStatus']);
        Route::resource('recibo', ReciboController::class);
        Route::resource('user', UserController::class);
        Route::post('user/action', [UserController::class, 'actionUser']);
        

        Route::resource('empresa', EmpresaController::class);
        Route::resource('timeUserSession', TimeUserSessionController::class);
        Route::resource('seguimiento', SeguimientoController::class);
        Route::resource('roles', RoleController::class);
        Route::resource('permisos', PermisoController::class);

        Route::controller(KpisController::class)->group(function () {
            Route::get('kpis', 'getTotalrecibo');
            Route::get('kpis/action', 'action')->name('kpis.action');
            Route::get('kpis/inicio', 'inicio')->name('kpis.inicio');
            Route::get('kpis/search', 'search')->name('kpis.search');
            Route::post('kpis/filter', 'searchFilter')->name('kpis.searchFilter');
        });

        //full calendar
        Route::get('calendar', [EventController::class, 'index'])->name('calendar.index');
        Route::post('calendar/create-event', [EventController::class, 'create'])->name('calendar.create');
        Route::post('calendar/edit-event', [EventController::class, 'edit'])->name('calendar.edit');
        Route::delete('calendar/remove-event', [EventController::class, 'destroy'])->name('calendar.destroy');
    });
}); //cierre log

//route:clear -- optimize:clear  //route-list

app/Models/Empresa.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Empresa extends Model
{
    use HasFactory;

    protected $fillable=[
        'nombre',
      
    ];

    public function nomina(){       
        return $this->hasMany(Nomina::class, 'empresa_id');
   }
}

app/Http/Controllers/EmpresaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Empresa as model;
use Yajra\DataTables\Facades\DataTables;

class EmpresaController extends Controller
{

    public function index(Request $request)
    {
        //https://www.youtube.com/watch?v=2P5f6RBfxYk
        if ($request->ajax()) {
            $items = model::all()
                ->where("total", "<", 100000);
            return datatables()->of($items)->addColumn('action', function ($item) {
                return '<a href="' . route('empresa.edit', $item->id) . '" class="btn btn-info btn-sm"> Editar 
                           </a>&nbsp;&nbsp;<button type="button" name="delete" data-id="' . $item->id . '" class="delete btn btn-danger btn-sm"> Eliminar </button>';
            })
                ->rawColumns(['action'])
                ->toJson();               
        }


        return view('empresa.index');
    }

    //no exoxste create porque se hace en la misma pagina del index
    public function store(Request $request)
    {

        $store = model::create([
            'nombre' => $request->input('nombre')
        ]);

        // return $store; exit;
        $store->save();

        return back();
    }


    public function show($id)
    {
        //
    }


    public function edit($id)
    {
        //
    }


    public function update(Request $request, $id)
    {
        //
    }


    public function destroy($id)
    {
        $item = model::findOrFail($id);
        $item->delete();
        return response()->json(['success' => true]);
    }
}

resources/views/empresa/create.blade.php
@extends('adminlte::page')
@section('title', 'deudas')

@section('content')
<section class="section">
    <div class="section-header">
        <h3 class="page_heading">Alta de deudas</h3>
    </div>
    <div class="section-body">
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">


                        @if ($errors->any())
                        <div class="alert alert-dark alert-dismissible fade show" deuda="alert">
                            <strong>Revise los campos!</strong>
                            @foreach($errors->all() as $error)
                            <span class="badge badge-danger">{{$error}}</span>
                            @endforeach
                            <button type="button" class="close" data-dismiss="alert" aria-label="close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        @endif

                        {!! Form::open(array('route'=>'deuda.store', 'method'=>'POST')) !!}
                        <div class="row">
                            <div class="col-xs-12 col-sm-12 col-md-12">
                            <div class="form-group">
                                    <label for="name">Fecha_Inicio</label>
                                    {!! Form::date('fecha_inicio', null, array('class'=>'form-control')) !!}
                                </div>

                                <div class="form-group">
                                    <label for="name">Nombre</label>
                                    {!! Form::text('nombre', null, array('class'=>'form-control', 'placeholder'=>'Nombre')) !!}
                                </div>

                                <div class="form-group">
                                    <label for="name">Fecha_fin</label>
                                    {!! Form::date('fecha_fin', null, array('class'=>'form-control')) !!}
                                </div>

                                <div class="form-group">
                            {!! Form::label('estado_deuda_id', 'Estado', ['class' =>'form-label']) !!}
                            <select name="estado_deuda_id" class="form-control">
                                @foreach($deuda as $d)
                                 <option value="{{$d->id}}">{{$d->nombre}}</option>                        
                                @endforeach
                            </select>
                                </div>

                                <div class="form-group">
                            {!! Form::label('Proceso_deuda_id', 'Proceso', ['class' =>'form-label']) !!}
                            <select name="Proceso_deuda_id" class="form-control">
                                @foreach($proceso as $p)
                                 <option value="{{$p->id}}">{{$p->nombre}}</option>                        
                                @endforeach
                            </select>
                                </div>                            
                               

                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <button type="submit" class="btn btn-primary">Guardar</button>
                                </div>
                            </div>
                        </div>

                        {!! Form::close() !!}



                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
</section>


@stop

resources/views/empresa/detail.blade.php
<!-- extiende del modal -->

@foreach ($items as $item)
<!--MODAL -->
<div class="modal fade" id="myModal-{{$item->id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">

  <div class="modal-dialog modal-lg modal-dialog-centered">  <!--modal-sm modal-xl  modal-lg-->
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Deuda {{$item->fecha}}</h5>
  

        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

      <table class="table table-striped">
    <thead>
      <tr>
        <th>user</th>
        <th>Fecha_inicio</th>
        <th>Nombre</th>
        <th>Fecha_fin</th>
        <th>Estado</th>
        <th>Progreso</th>
          
      </tr>
    </thead>
    <tbody>     
      <tr>
     
        <td>{{$item->user->name}}</td>
        <td>{{$item->fecha_inicio}}</td>
        <td>{{$item->nombre}}</td>
        <td>{{$item->fecha_fin}}</td>
        <td>{{@$item->estado->nombre}}</td>
        <td>{{$item->proceso->nombre}}</td>
       
      </tr>
    </tbody>
  </table>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>  
</div>
<!-- /. modal content-->
@endforeach

resources/views/empresa/edit.blade.php
@extends('adminlte::page')
@section('title', 'deudas')

@section('content')
<section class="section">
    <div class="section-header">
        <h3 class="page_heading">Actualizar campos</h3>
    </div>
    <div class="section-body">
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">


                        @if ($errors->any())
                        <div class="alert alert-dark alert-dismissible fade show" deuda="alert">
                            <strong>Revise los campos!</strong>
                            @foreach($errors->all() as $error)
                            <span class="badge badge-danger">{{$error}}</span>
                            @endforeach
                            <button type="button" class="close" data-dismiss="alert" aria-label="close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        @endif

                        {!! Form::model($edit, ['route' => ['deuda.update', $edit->id], 'method' => 'PUT']) !!}

                        <div class="row">
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <label for="name">Fecha_Inicio</label>
                                    {!! Form::date('fecha_inicio', $edit->fecha_inicio, array('class'=>'form-control')) !!}
                                </div>

                                <div class="form-group">
                                    <label for="name">Nombre</label>
                                    {!! Form::text('nombre', $edit->nombre, array('class'=>'form-control')) !!}
                                </div>

                                <div class="form-group">
                                    <label for="name">Fecha_fin</label>
                                    {!! Form::date('fecha_fin', $edit->fecha_fin, array('class'=>'form-control')) !!}
                                </div>

                                <div class="form-group">
                                    {!! Form::label('Estado:  '. $edit->estado->nombre) !!}
                                    <select name="estado_deuda_id" class="form-control">
                                        @foreach($deuda as $d)
                                        <option value="{{$d->id}}">{{$d->nombre}}</option>
                                        @endforeach
                                    </select>
                                </div>

                                <div class="form-group">
                                    {!! Form::label('proceso: '. $edit->proceso->nombre) !!}
                                    <select name="Proceso_deuda_id" class="form-control">
                                        @foreach($proceso as $p)
                                        <option value="{{$p->id}}">{{$p->nombre}}</option>
                                        @endforeach
                                    </select>
                                </div>

                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <button type="submit" class="btn btn-primary">Update</button>
                                </div>
                            </div>
                        </div>

                        {!! Form::close() !!}



                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
</section>


@stop

resources/views/empresa/index.blade.php
@extends('adminlte::page')

@section('title', 'items')

@section('content_header')
<h1>Listado de Empresas</h1>
@stop

@section('content')

<div class="col-lg-12 mt-2">
    <div class="card w-100 h-100">
        <div class="card-body">
            <h7 class="text-right">Registro de cuentas: {{ auth()->user()->name }}</h7>

            <br>
            <div class="text-right">
                <a href="{{route('cuenta.create')}}" class="btn btn-primary mb-3">Crear Registro</a>
            </div>

            <div class="table-responsive">
                <table id="items" class="table table-hover table-striped table-bordered table-sm" style="width:100%;">
                    <thead>
                        <tr>
                            <th scope="col">id</th>
                            <th scope="col">nombre</th>
                            <th scope="col">creacion</th>                          
                            <th scope="col">acciones</th>

                        </tr>

                    </thead>

                </table>
            </div>

        </div>
    </div>
</div>

@stop

@section('js')

@include('layouts.datatable', [
'ajaxUrl' => route('empresa.index'),
'columns' => json_encode([
['data' => 'id'],
['data' => 'nombre'],
['data' => 'created_at'],

['data' => 'action', 'orderable' => false],
])
])

@include('layouts.delete', ['deleteUrl' => "empresa"])


@stop